<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email Address Field Error Msg</name>
   <tag></tag>
   <elementGuidId>9a6838a6-8057-44b0-b50d-18829f015b67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='EmailFormat_passengerEmail-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EmailFormat_passengerEmail-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#EmailFormat_passengerEmail-error</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3121c44-ae7d-45e4-8a6a-6b7e2f174427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailFormat_passengerEmail-error</value>
      <webElementGuid>1820ea07-8168-4142-a778-c9f045324309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Field required</value>
      <webElementGuid>21c27c9e-d746-4df1-a60d-6b8f9b1b446c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailFormat_passengerEmail-error&quot;)</value>
      <webElementGuid>e42b4e89-1787-4733-9b5d-3982bf8758c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='EmailFormat_passengerEmail-error']</value>
      <webElementGuid>2d74ba2b-dc32-4c98-a389-046a86d90328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CollapseCP']/div/div[3]/div/span/span</value>
      <webElementGuid>4c5301a2-d242-4a36-a831-b2c668d707c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail Address'])[1]/following::span[2]</value>
      <webElementGuid>65b0e63e-c23f-4975-a6d0-7cb50c263e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Field required'])[6]/following::span[2]</value>
      <webElementGuid>baaa7f37-a776-430a-bbce-56457ad9a3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::span[1]</value>
      <webElementGuid>2f5e9673-af46-46ae-ae87-920653f558ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::span[2]</value>
      <webElementGuid>0bbf6e50-26d5-4d67-8509-02d6d838ecab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/span</value>
      <webElementGuid>50905e8f-3dda-4cab-8515-9a87c3092422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'EmailFormat_passengerEmail-error' and (text() = 'Field required' or . = 'Field required')]</value>
      <webElementGuid>2f964d1b-22e3-4ab4-9630-8ca41e9a9786</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
