<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Coupons Requested_couponsToRefund</name>
   <tag></tag>
   <elementGuidId>b675d2e1-60d8-4146-92a6-2c1be83231b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CouponFormat_couponsToRefund']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CouponFormat_couponsToRefund</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CouponFormat_couponsToRefund</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>519adcf0-2245-42ed-9ef4-c55019402820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm valid</value>
      <webElementGuid>fe622375-3a8e-476e-be00-bf2f07bb4f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9234e585-c93d-402c-83a7-455945961e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>Length must be less than or equal to 20 characters</value>
      <webElementGuid>437d54e6-027c-4aba-a561-65f95166e00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8e7dab24-d195-47fa-8c38-6b566063aa79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Coupon format is incorrect. It should be: 1234/1234/12</value>
      <webElementGuid>20eeae8a-42df-4b3a-9c08-17e07c49ce82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>(^1?2?3?4?(\/1?2?3?4?)*$)</value>
      <webElementGuid>26010d5b-4c31-4b89-aa60-08c3b3e2b158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CouponFormat_couponsToRefund</value>
      <webElementGuid>a0290fa3-e13e-4b84-8473-9b05b64b6e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>couponsToRefund</value>
      <webElementGuid>3a3fa77f-06e8-45cf-b24b-c89dd069f0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>RequestCardMain.refreshCouponsInFacsimile(refundMain.vars, false);</value>
      <webElementGuid>51fb8667-0bda-4f32-9876-b56b17986dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3bb5e5a9-cb91-46e9-854d-a7ef357477a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>CouponFormat_couponsToRefund-error</value>
      <webElementGuid>36390147-a220-40f8-b2fb-2d524bfa8ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>147addec-e0a9-4031-9060-56a3cdadc471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CouponFormat_couponsToRefund&quot;)</value>
      <webElementGuid>fa348716-9181-4f42-9ab2-a1e8b91f70a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CouponFormat_couponsToRefund']</value>
      <webElementGuid>4c0b91b8-b37a-4036-a087-db11c56ea4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CollapseCR']/div/div/div[3]/input</value>
      <webElementGuid>9e2c5305-384d-411b-acbc-d8b54fdb3129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>bd53c3bb-12ac-48c2-b76f-ef641d719da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CouponFormat_couponsToRefund' and @name = 'couponsToRefund' and @type = 'text']</value>
      <webElementGuid>53a0ddcd-1a53-4b06-951a-a5b9b1ebc6c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
