<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail Address_passengerEmail</name>
   <tag></tag>
   <elementGuidId>4b5d9014-0480-4ddc-87ee-d12316faaf4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmailFormat_passengerEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EmailFormat_passengerEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#EmailFormat_passengerEmail</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>301a6d86-dfa8-4d8b-ac9e-c3fcddcd2576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm clToUpperCase input-validation-error</value>
      <webElementGuid>db30012e-8112-4d45-a71b-70cc31633d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f258f52a-8018-408e-8ff8-ff11986ef7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>Length must be less than or equal to 200 characters</value>
      <webElementGuid>52683e5f-2578-4466-9b7c-796d3cfa2257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>7239beb8-9e4d-4eeb-8088-b1cf2ec179f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>The e-mail Address field is not a valid e-mail address.</value>
      <webElementGuid>bb359bab-286e-4eb6-8ca0-18ab9c22b11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*((\s)*,(\s)*(\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*))*$</value>
      <webElementGuid>e84eb341-0cc7-4931-89c6-f9938b5ca182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailFormat_passengerEmail</value>
      <webElementGuid>9a196b00-8d86-4be2-b4d0-0c63cfc64cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passengerEmail</value>
      <webElementGuid>3484f227-d6ae-49e6-89b0-8725a5954fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f10aeb0d-e2fe-4002-be95-ae59f1db13fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>EmailFormat_passengerEmail-error</value>
      <webElementGuid>38c56e07-64b5-405d-a06a-c8e73b300172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailFormat_passengerEmail&quot;)</value>
      <webElementGuid>b5d2e4b5-55d4-4c37-8176-2479d94e9055</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmailFormat_passengerEmail']</value>
      <webElementGuid>e8a20505-4fdc-4945-8ad1-67a2bbc1fdb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CollapseCP']/div/div[3]/input</value>
      <webElementGuid>d1768524-5d0a-4a68-a1ed-1cf152f8f9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div[3]/input</value>
      <webElementGuid>f235ded0-6d22-4d9b-8708-e7ab94bbf439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EmailFormat_passengerEmail' and @name = 'passengerEmail' and @type = 'text']</value>
      <webElementGuid>1de2e6ca-b40e-456f-98ec-8a671e66939e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
