<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CACCFT</name>
   <tag></tag>
   <elementGuidId>db7e1c1f-42fa-417f-8638-33a1d7a27e2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='requestedFop']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#requestedFop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Requested FOP&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>82405081-d894-4bfd-b723-270375aab732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm input-validation-error</value>
      <webElementGuid>e630a4a9-1fa7-4c7b-adca-3256705162d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>requestedFop</value>
      <webElementGuid>17345294-55aa-43be-86c4-4fb6149096e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>requestedFop</value>
      <webElementGuid>b1c362e6-824f-4620-9ac5-bc8f25d7b33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ae4f2ef0-aa0c-4e5c-87fa-6eed31dd5f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>requestedFop-error</value>
      <webElementGuid>3c33033e-b835-40e2-95c4-b3946c1df149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9572d90b-4faf-44db-b5ba-2996e83739bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
CA
CC
FT
</value>
      <webElementGuid>76c03b9b-3847-4d68-9997-fba7c6d1a570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requestedFop&quot;)</value>
      <webElementGuid>cccf990d-c2a1-41c7-b219-c858a9b7597f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='requestedFop']</value>
      <webElementGuid>c3ff5b90-d73d-4479-98b8-0fb5175ab76e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CollapseCR']/div/div/div[2]/div/select</value>
      <webElementGuid>5c0b4b9b-9ca7-4e5d-bf53-435c94193132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requested FOP'])[1]/following::select[1]</value>
      <webElementGuid>544e0ce0-e757-4324-b424-8b6d424a9ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requested Amount'])[1]/following::select[1]</value>
      <webElementGuid>d52ab216-b5b7-42e5-a561-355fc0b6faf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Field required'])[1]/preceding::select[1]</value>
      <webElementGuid>a38e8963-83a6-4dd9-842a-6b5636955da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coupons Requested'])[1]/preceding::select[1]</value>
      <webElementGuid>828f97a6-2c6a-404d-8f95-a90d966cffd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/select</value>
      <webElementGuid>880483cf-e3b5-46a9-99a6-31c367efd4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'requestedFop' and @name = 'requestedFop' and (text() = '
CA
CC
FT
' or . = '
CA
CC
FT
')]</value>
      <webElementGuid>cebcdfad-b1a6-444c-ab65-4fd7f88382ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
