<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Refund Capture</name>
   <tag></tag>
   <elementGuidId>6f7ce440-2d90-4b98-bc64-a8e87aa6e22f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_RefundsCapture</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_RefundsCapture']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Refund Capture&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b93c7ad-5cf5-469e-80bb-b910404d9c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_RefundsCapture</value>
      <webElementGuid>ef772b9f-ba0b-4b3f-ba0d-7388f3bb94a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>f719f3d5-d91f-40a1-8d1a-1f10fe031244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/MozartTest/RefundsCapture/Index</value>
      <webElementGuid>3e46dd1d-2def-489c-90a5-8300270e3bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Refund Capture
                    </value>
      <webElementGuid>01d41c10-5a06-47ad-b65f-e9e610c6c069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_RefundsCapture&quot;)</value>
      <webElementGuid>e4088162-864e-46f6-a75b-a3059eb8a55d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_RefundsCapture']</value>
      <webElementGuid>db38c9f7-c7ca-4184-b358-d9d6b4fca48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul/li/ul/li/a</value>
      <webElementGuid>0e969822-9653-47d6-a2c2-c54c6826c085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Refund Capture')]</value>
      <webElementGuid>7b85daa4-4aee-4d1b-996f-98cb506f2b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mozart - Refund Management'])[1]/following::a[2]</value>
      <webElementGuid>57ff6cc7-ae6c-4263-9601-ffd1d481ee72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refund Search'])[1]/preceding::a[1]</value>
      <webElementGuid>a21097e3-b9d8-437c-8d48-2e95630bf45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Refund Capture']/parent::*</value>
      <webElementGuid>f605583c-9e62-460d-bb33-0918ac2be386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/MozartTest/RefundsCapture/Index')]</value>
      <webElementGuid>3e8beeb9-bfb6-40f9-aee5-bd0c9cbf2831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>48395bee-72e6-4ab6-96d9-b8c4370d563a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu_RefundsCapture' and @href = '/MozartTest/RefundsCapture/Index' and (text() = '
                        Refund Capture
                    ' or . = '
                        Refund Capture
                    ')]</value>
      <webElementGuid>fe857a6a-9728-4fed-839e-ee407135163d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
