<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search by ticket number</name>
   <tag></tag>
   <elementGuidId>20dbdc15-078f-453d-96a7-6b9d9d61a165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.dropdown-toggle.btn-light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox[name=&quot;Search by ticket number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f2271479-9f12-470d-a942-eb849e61beff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c1889fa-59af-4e64-98ba-e79ced62fcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn dropdown-toggle btn-light</value>
      <webElementGuid>628309d8-f891-429e-a204-ca50962b9e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>34ffe48b-38b2-400f-aea0-d3f0227bb0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>c4f12a79-87c5-4c9b-a880-ccec90ff38ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>bs-select-5</value>
      <webElementGuid>ddf93a0e-9781-482d-97a3-84b6c977d21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>979433c1-e61e-4adc-a71d-18bb509b99c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>78bd7f51-9bb4-4e7a-8ad7-d01aee4340b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>advancedFilter_selectedadvfilter</value>
      <webElementGuid>7c872995-249d-4a34-b6ef-b73bc86b2e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search by ticket number</value>
      <webElementGuid>e9d4766e-07c3-4cf1-8730-a98f2e4b0b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search by ticket number </value>
      <webElementGuid>765e93c9-86a4-46bb-8c0e-de6e9154ed4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AdvancedfiltersPartialPage&quot;)/div[@class=&quot;pb-2&quot;]/div[@class=&quot;d-flex flex-row flex-wrap pl-1&quot;]/div[@class=&quot;d-flex flex-column pr-1&quot;]/div[@class=&quot;nomargin filter-input&quot;]/div[@class=&quot;dropdown bootstrap-select form-control form-control-sm filter-input NOdisabledInCaseRO show&quot;]/button[@class=&quot;btn dropdown-toggle btn-light&quot;]</value>
      <webElementGuid>01de4221-6cc8-4ee7-b3f2-00020471805a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>14cbaf95-bddd-4eb0-a452-679d7d05b4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AdvancedfiltersPartialPage']/div/div/div/div[2]/div/button</value>
      <webElementGuid>9d19d6e1-912a-4c10-b816-4207306df4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search type'])[1]/following::button[1]</value>
      <webElementGuid>638d4c71-1111-4ef5-a39b-a74712ae3f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXCEL'])[1]/following::button[1]</value>
      <webElementGuid>4d0d33d5-8b6c-47c0-aa40-eb48abc02729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search by ticket number'])[3]/preceding::button[1]</value>
      <webElementGuid>53e9f708-b211-4985-82b0-16bffc69b63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>5bf47ea2-b2a1-4986-afd9-a7e7f6f060f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Search by ticket number' and (text() = 'Search by ticket number ' or . = 'Search by ticket number ')]</value>
      <webElementGuid>e976f0a4-8123-4ca6-96c3-f3a6799d6a02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
