<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Value_advancedFilter.idrequest</name>
   <tag></tag>
   <elementGuidId>0045b007-89c5-4445-8d1d-814de050eadd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='advancedFilter_idrequest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advancedFilter_idrequest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Please enter a valid request Id (exact match)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec238091-72e3-42f3-bf89-e0bead0d17b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm NOdisabledInCaseRO</value>
      <webElementGuid>bba8986f-0179-4fa9-880f-4be21bed6168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fbc1e343-80b2-4381-b7fe-7d2138353f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Invalid format</value>
      <webElementGuid>b1c09485-e499-41c7-bb6a-24f2abdfbd0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>(^[\s]*[A-Za-z]{1}[0-9]{4}[A-Za-z0-9]{5}[\s]*$)</value>
      <webElementGuid>926f792b-f79e-4045-a043-0847f8cb0c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advancedFilter_idrequest</value>
      <webElementGuid>86100e6d-6e1d-4e64-a3a6-0bce7efb5ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>advancedFilter.idrequest</value>
      <webElementGuid>8223daae-3e2e-45cb-bf1a-d43956f4e83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>FilterHelper.fillOtherComponent($(this))</value>
      <webElementGuid>35c33b10-4d5f-45a1-b32c-524ed40860d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter a valid request Id (exact match)</value>
      <webElementGuid>c672e75f-5dd6-4bc9-9f87-b84d3746c83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41e79ba8-d623-485e-8496-133713c5252b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advancedFilter_idrequest&quot;)</value>
      <webElementGuid>b55e082d-7944-4a2a-8d4f-e7b5ac921500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='advancedFilter_idrequest']</value>
      <webElementGuid>8c8dfa8d-7124-4e64-9b9f-feb2663ef4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AdvancedfiltersPartialPage']/div/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>5ff43c33-8d32-473f-b4c0-bc9e14fdf808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>5715e16b-6207-4e69-b4c6-8f2410fc6c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'advancedFilter_idrequest' and @name = 'advancedFilter.idrequest' and @placeholder = 'Please enter a valid request Id (exact match)' and @type = 'text']</value>
      <webElementGuid>c3a86191-9548-4306-bfb1-e461ba599325</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
