<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Value_advancedFilter.idrequest</name>
   <tag></tag>
   <elementGuidId>8a149ad7-c783-499c-a4c4-bd70ec69071f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='advancedFilter_idrequest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advancedFilter_idrequest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Please enter a valid request Id (exact match)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdb1f3e5-fe71-4655-8965-ab8e8f9ef4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm NOdisabledInCaseRO</value>
      <webElementGuid>34a75add-790d-4414-aeb9-0270f4823671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ba6dfd99-f6de-4ed2-8934-eaabf0a1833e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Invalid format</value>
      <webElementGuid>77e5c224-c0cf-4575-9960-577e1e2eb6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>(^[\s]*[A-Za-z]{1}[0-9]{4}[A-Za-z0-9]{5}[\s]*$)</value>
      <webElementGuid>6b44d4c1-5a56-4ecb-88c4-9a78d2c14db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advancedFilter_idrequest</value>
      <webElementGuid>8a28a941-2063-4469-bb53-c93d7dc541bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>advancedFilter.idrequest</value>
      <webElementGuid>e3a33986-a3fc-4ad9-9f3c-e215bb6b13b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>FilterHelper.fillOtherComponent($(this))</value>
      <webElementGuid>31f69ee6-c6c5-4406-be8a-e8e3c563bed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter a valid request Id (exact match)</value>
      <webElementGuid>526d0b07-1df7-44de-991b-7e2fd7d56201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad39d240-7ba0-462c-8e0e-3d32ea563676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advancedFilter_idrequest&quot;)</value>
      <webElementGuid>c2171740-6953-4cf4-a646-3f85590b93f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='advancedFilter_idrequest']</value>
      <webElementGuid>3a2b6116-6aa1-4d0c-b47d-423f9b32bce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AdvancedfiltersPartialPage']/div/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>50c062cf-b02f-408d-a595-0415afa6d5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>c48c8b02-5ef5-4f68-aadb-f23f3b69872f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'advancedFilter_idrequest' and @name = 'advancedFilter.idrequest' and @placeholder = 'Please enter a valid request Id (exact match)' and @type = 'text']</value>
      <webElementGuid>a84f488d-8233-4bc5-840e-8a9bbbdb9acf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
