<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_ranajit.vadaraccelya.com</name>
   <tag></tag>
   <elementGuidId>c0f35c30-ec53-44b0-a253-c0148bdd511a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='tr_182']/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;ranajit.vadar@accelya.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d45252bc-7485-437c-a948-53f67c8e222d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> width200px</value>
      <webElementGuid>da44ea73-9dc2-473a-81fd-be922892c4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        ranajit.vadar@accelya.com
    </value>
      <webElementGuid>e1d96bff-467b-415c-95c8-634d5f68d3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tr_182&quot;)/td[@class=&quot;width200px&quot;]</value>
      <webElementGuid>40f3b3ba-6cd6-426d-a7cf-f4534e89ec94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_182']/td[3]</value>
      <webElementGuid>e35d2dc6-badd-4b15-9aaa-ebc4b345ed89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ranajitvadar'])[2]/following::td[1]</value>
      <webElementGuid>d859d2b0-27fe-4614-8479-4bde0f739bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ranajitvadar'])[1]/following::td[2]</value>
      <webElementGuid>7500dba8-84e8-43c1-b627-dad16db661dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WEB_SERVICE_CAPTURE'])[4]/preceding::td[2]</value>
      <webElementGuid>987a12d4-afcc-4478-bed4-9feb19e4f9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SuperMozart'])[6]/preceding::td[4]</value>
      <webElementGuid>45b44a85-5275-452e-9f7b-b8ee57a82d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ranajit.vadar@accelya.com']/parent::*</value>
      <webElementGuid>15ab5b27-b05a-4b2c-ab55-5ae152840047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[3]</value>
      <webElementGuid>17a92882-66b2-4191-baa4-8848955e5dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
        ranajit.vadar@accelya.com
    ' or . = '
        ranajit.vadar@accelya.com
    ')]</value>
      <webElementGuid>5b9e4a3b-68b3-4c1e-b5b5-2e18e85b4e54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
