<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_ranajitvadar</name>
   <tag></tag>
   <elementGuidId>45f0bb85-9d95-44bd-a0f6-3c1ace0e694d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='tr_182']/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;ranajitvadar&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>aa058e6b-a9bf-4219-93ef-3c01c3d6e0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> width200px</value>
      <webElementGuid>deb893e3-091f-412a-9451-c3218ccb4f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        ranajitvadar
    </value>
      <webElementGuid>3c26c893-7bf4-4baa-b114-e17666b089f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tr_182&quot;)/td[@class=&quot;width200px&quot;]</value>
      <webElementGuid>bca9c434-44ea-43fa-8aae-fecdb87e048d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_182']/td[2]</value>
      <webElementGuid>d271f7f4-0e4b-4ae3-a2e5-7396dd8c836c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ranajitvadar'])[1]/following::td[1]</value>
      <webElementGuid>7f28570f-f5a4-467d-a53e-5d8cce671943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cancel'])[15]/following::td[2]</value>
      <webElementGuid>3847a5a4-a786-4bc9-bd06-6c4c7c69f5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ranajit.vadar@accelya.com'])[1]/preceding::td[1]</value>
      <webElementGuid>2b0db48e-901d-4e4e-8532-943b5c2e60bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WEB_SERVICE_CAPTURE'])[4]/preceding::td[3]</value>
      <webElementGuid>2102f971-50d0-4335-b3de-cc64581c62ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[2]</value>
      <webElementGuid>8eeda18a-d504-44a8-a323-9cbdea4fbdb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
        ranajitvadar
    ' or . = '
        ranajitvadar
    ')]</value>
      <webElementGuid>32068e7b-7b8a-4438-8a71-492a8cb13a49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
