<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>couponsRequested_TextBox</name>
   <tag></tag>
   <elementGuidId>b4e3584e-b8f0-400f-8f79-7f117f986e33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CouponFormat_couponsToRefund</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CouponFormat_couponsToRefund']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CouponFormat_couponsToRefund</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d080f0b7-8fe7-4c6f-9aa4-70bc17cb8092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm valid</value>
      <webElementGuid>981892c0-ee61-458b-a0ae-ed8bced32efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f473a044-a937-4a5f-83e5-362564eadc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>Length must be less than or equal to 20 characters</value>
      <webElementGuid>a0a107f8-1006-4141-98d9-fc348c999ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>3bce0653-fc33-4746-8cd1-b4573ca4d91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Coupon format is incorrect. It should be: 1234/1234/12</value>
      <webElementGuid>acac0777-7c39-44d9-99e4-96d34bfce735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>(^1?2?3?4?(\/1?2?3?4?)*$)</value>
      <webElementGuid>2e10f438-7776-4d1a-8521-22d10d4d3c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CouponFormat_couponsToRefund</value>
      <webElementGuid>ecc0e1d8-36b1-4abd-a4d2-6b71bc487891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>couponsToRefund</value>
      <webElementGuid>4005fe5c-1c1a-4bdb-bc2c-3abef82fbb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>RequestCardMain.refreshCouponsInFacsimile(refundMain.vars, false);</value>
      <webElementGuid>d266fdcd-8d9e-4db3-a957-81e26fc6e914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4f0efe8-d8e3-4ada-8332-49276997520d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>CouponFormat_couponsToRefund-error</value>
      <webElementGuid>32ae216d-acf9-427e-a797-e63f93eaccdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4455d2cf-2d25-4d66-b3fd-b9dadcbd68ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CouponFormat_couponsToRefund&quot;)</value>
      <webElementGuid>110a9e30-555e-43ca-9e7d-e558a31d35d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CouponFormat_couponsToRefund']</value>
      <webElementGuid>fdb7c06b-6f2a-4fa2-82bf-74b4fd23e2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CollapseCR']/div/div/div[3]/input</value>
      <webElementGuid>13259af7-bb3d-43fd-9863-36d2e48f3e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>d8b56857-e13f-48cf-80d8-8b23ef75820f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CouponFormat_couponsToRefund' and @name = 'couponsToRefund' and @type = 'text']</value>
      <webElementGuid>5dac88f5-7960-4bcb-a702-87ce9a9fd92a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
