<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Country</name>
   <tag></tag>
   <elementGuidId>eeed7e87-9936-4a31-aeb8-4f1856d9f125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.filter-option-inner-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='formSearchForDocument']/div/div/div[4]/div/div/div/button/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox[name=&quot;Country&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e60669c3-358d-4f7d-80ff-f3cfe8978e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-option-inner-inner</value>
      <webElementGuid>1f07ebe8-6758-44ec-8610-a347272b68a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Country</value>
      <webElementGuid>04e6e8bc-4b3c-4a93-b307-f8bcbd5b5880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSearchForDocument&quot;)/div[@class=&quot;d-flex flex-wrap justify-content-between&quot;]/div[@class=&quot;d-flex row row-reduced justify-content-start flex-wrap&quot;]/div[@class=&quot;align-self-center pr-1&quot;]/div[@class=&quot;flex-column&quot;]/div[@class=&quot;flex-row&quot;]/div[@class=&quot;dropdown bootstrap-select form-control form-control-sm country disabledInCaseRO&quot;]/button[@class=&quot;btn dropdown-toggle btn-light is-invalid&quot;]/div[@class=&quot;filter-option&quot;]/div[@class=&quot;filter-option-inner&quot;]/div[@class=&quot;filter-option-inner-inner&quot;]</value>
      <webElementGuid>9e4749db-81ca-485f-9821-61b868331dc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSearchForDocument']/div/div/div[4]/div/div/div/button/div/div/div</value>
      <webElementGuid>78421919-d5be-4c45-aede-346dc9b08920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refund Capture'])[4]/following::div[17]</value>
      <webElementGuid>db8b2ee0-ca05-4e69-9a49-88eb22bd1f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='flight'])[1]/following::div[17]</value>
      <webElementGuid>9d740826-73f3-4184-b9fc-961d9a26f302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Field required'])[1]/preceding::div[4]</value>
      <webElementGuid>af9d7637-7e49-46c3-8cbb-0ecaf4606382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Pax'])[1]/preceding::div[5]</value>
      <webElementGuid>acc5813c-aa99-4a8b-a40c-4183653a6d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div</value>
      <webElementGuid>40dda669-2880-4b95-98a9-08fa36b83e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Country' or . = 'Country')]</value>
      <webElementGuid>597a156e-a29f-4a1a-a35c-b763ff2860b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
