<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Refund correctly sent</name>
   <tag></tag>
   <elementGuidId>0f4b540c-7e1b-4f1d-8d4a-a97461e6d757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.toast-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast_6021']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#toast_6021 div >> internal:has-text=&quot;Refund correctly sent.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>796d56bd-5a64-4de8-bbbd-8fb2cd4a205e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toast-body</value>
      <webElementGuid>a102f94c-1c00-4865-9fdd-0de4d646543f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Refund correctly sent.</value>
      <webElementGuid>69000c8e-e591-4cc5-8d52-2e0b4635a387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast_6021&quot;)/div[@class=&quot;toast-body&quot;]</value>
      <webElementGuid>df3f37cc-9117-4939-b634-86cc308f28de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast_6021']/div[2]</value>
      <webElementGuid>a07a5342-7c98-4f3d-a4e2-a4b32dedbc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success'])[1]/following::div[1]</value>
      <webElementGuid>34ebd354-612b-4afd-9d27-586853c37c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In progress'])[1]/following::div[6]</value>
      <webElementGuid>f54e17b4-a83d-45b1-889e-312307075fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]</value>
      <webElementGuid>d1264636-1cf6-42c0-85c2-a3c9f9ca0d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Refund correctly sent.' or . = ' Refund correctly sent.')]</value>
      <webElementGuid>0996e200-816b-4b15-88a1-43c45aca412e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
