<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailAddress_PassengerDetails_TextBox</name>
   <tag></tag>
   <elementGuidId>596fa2ab-0e1b-49ac-bbf5-4e7d0a60dc16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EmailFormat_passengerEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmailFormat_passengerEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#EmailFormat_passengerEmail</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b426db5-c636-4b4f-b1cb-7159b27db90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm clToUpperCase input-validation-error</value>
      <webElementGuid>cae4d8bc-3e1e-4e48-91e7-8f2daf4c1d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ca4f2818-cf4d-452e-8c17-343b4a9e7d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>Length must be less than or equal to 200 characters</value>
      <webElementGuid>814b5513-97f6-4926-a8fc-df4e08fb272f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>e3885a55-2418-4b98-b999-6d63361598bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>The e-mail Address field is not a valid e-mail address.</value>
      <webElementGuid>ae57ecd6-e850-4882-b502-cbdc2f3774c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*((\s)*,(\s)*(\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*))*$</value>
      <webElementGuid>8359a0aa-9679-46c3-8ec0-db3629654dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailFormat_passengerEmail</value>
      <webElementGuid>601a1d31-fd6a-40c9-9df2-c3c86632ffaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passengerEmail</value>
      <webElementGuid>7e342b17-ab6d-4af9-b1f2-e2f1205c48cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34e0df62-2dd5-4253-a13e-54970333c79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>EmailFormat_passengerEmail-error</value>
      <webElementGuid>4e1761ae-d427-4243-946a-3dffae3208a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailFormat_passengerEmail&quot;)</value>
      <webElementGuid>0d131033-1576-4282-94a9-f672d6a1f672</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmailFormat_passengerEmail']</value>
      <webElementGuid>ef152b64-7315-4032-84ca-f316d2c4d154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CollapseCP']/div/div[3]/input</value>
      <webElementGuid>83b1adef-0ce7-4aa7-a43e-aa4ac68b6b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div[3]/input</value>
      <webElementGuid>59ad5aa1-89f1-481b-a4c2-c598b748cb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EmailFormat_passengerEmail' and @name = 'passengerEmail' and @type = 'text']</value>
      <webElementGuid>573fcc49-a484-4099-a745-f319cd2b868c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
