<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EnterDocumentNumber</name>
   <tag></tag>
   <elementGuidId>aca23e9f-527e-4ee3-8e18-8b3657ec6c22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NumberFormat_documentNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NumberFormat_documentNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ticket Number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f05c1d8-3cf6-40b8-b249-df0ad49b9e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm clToUpperCase input-validation-error is-invalid</value>
      <webElementGuid>5ca2b816-4662-4abe-9e49-12adb9759348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NumberFormat_documentNumber</value>
      <webElementGuid>a7fba67d-f0fa-4db3-a1c9-25f4571d5969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>documentNumber</value>
      <webElementGuid>58469bce-7ab8-4813-a1be-e43f35b59007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CRequestCardMain.enableCoupons($(this))</value>
      <webElementGuid>5ff18863-4196-40a1-aa21-7cad7b0d7297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ticket Number</value>
      <webElementGuid>e0dad35e-3214-4d69-8e4d-856530698cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b0d70e1-f712-48c4-9314-f76f77441249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>NumberFormat_documentNumber-error</value>
      <webElementGuid>ff3adb51-10a1-4122-b202-9de7f3be7def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NumberFormat_documentNumber&quot;)</value>
      <webElementGuid>6948d97c-c370-4e0d-905c-0dc67693d10b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NumberFormat_documentNumber']</value>
      <webElementGuid>db9e11d3-7dfe-4d12-9165-d5b304dbe659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSearchForDocument']/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>7693c7c2-be1c-4c91-ae9e-88708127db49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>9ce3e2a6-3fdc-4aac-a76f-871c65f5a02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NumberFormat_documentNumber' and @name = 'documentNumber' and @placeholder = 'Ticket Number' and @type = 'text']</value>
      <webElementGuid>59592d15-6884-47ab-a9f3-863651486fa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
