<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Save_mdi mdi-send pr-1</name>
   <tag></tag>
   <elementGuidId>6dab9bf8-f7a3-47ee-9b56-cba838f2331e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-send.pr-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sendBtn']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Send&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b1bca06a-9379-4ece-a8e6-9e428866d2bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-send pr-1</value>
      <webElementGuid>e8a02f5c-325f-4c66-9586-ef5b57e554b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sendBtn&quot;)/i[@class=&quot;mdi mdi-send pr-1&quot;]</value>
      <webElementGuid>00dcc19d-1a36-4539-8f52-70c6911dbd36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='sendBtn']/i</value>
      <webElementGuid>f491e416-b9bd-4369-9636-572033c65ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/i</value>
      <webElementGuid>2f8596a5-635a-4e47-9d84-6b840c17d2e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
