<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Country_form-control</name>
   <tag></tag>
   <elementGuidId>b9fe1ff4-d2d2-47b5-b679-997fd8392f8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bs-searchbox > input.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>119dcd1d-0a37-4eb3-966b-ca9e48b410ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>66a7913c-2805-4539-9a4b-21b07b6ab6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cbed53e0-10d0-464f-b261-ee06c3674ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>05c2fb07-58ca-4272-8571-16d81d6f4719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>074e2331-f7e6-45ae-a087-37961f4eba99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>1776363b-cb63-499e-a604-5d9e896bc930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>bs-select-1</value>
      <webElementGuid>ffb10501-b8ef-4431-b3c3-573c08cef49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>dd0bc27e-ee6c-410a-bdd2-49accb093b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>bs-select-1-0</value>
      <webElementGuid>57f68f41-869d-4516-9018-eee446bd8d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSearchForDocument&quot;)/div[@class=&quot;d-flex flex-wrap justify-content-between&quot;]/div[@class=&quot;d-flex row row-reduced justify-content-start flex-wrap&quot;]/div[@class=&quot;align-self-center pr-1&quot;]/div[@class=&quot;flex-column&quot;]/div[@class=&quot;flex-row&quot;]/div[@class=&quot;dropdown bootstrap-select form-control form-control-sm country disabledInCaseRO show&quot;]/div[@class=&quot;dropdown-menu show&quot;]/div[@class=&quot;bs-searchbox&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>56ac6cc7-fd01-4772-819d-6e53c8add1a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='search']</value>
      <webElementGuid>bfccd1e2-65c4-436d-9818-f68a6e8834fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSearchForDocument']/div/div/div[4]/div/div/div/div/div/input</value>
      <webElementGuid>7aad471f-d513-49bc-b0be-8b4961794298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/input</value>
      <webElementGuid>1bf071e5-341f-467a-b1ce-1a1e9ab0d026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search']</value>
      <webElementGuid>0d366b76-0891-4f50-9eec-c3e43ec1b6e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
