<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>passengerRemarks_TextBox</name>
   <tag></tag>
   <elementGuidId>1d18204d-0396-4ec5-8315-88ed93639146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#agentComment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='agentComment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#agentComment</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>aa775246-aac3-4588-baaa-8ce16787fcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control valid</value>
      <webElementGuid>95c33da3-d603-43e8-8bcf-13f2b687897b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4dc05207-89de-4c6e-80c8-c049f881084d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56ef434a-6777-4d2e-b21d-7cc71f11ce3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>Length must be less than or equal to 5000 characters</value>
      <webElementGuid>46e0ff56-57ea-480d-af22-de0597792f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>5000</value>
      <webElementGuid>9fece3ad-7269-40b6-92b8-125186e84814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agentComment</value>
      <webElementGuid>1e468a72-cb23-4cd2-85b6-719aef2f0821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5000</value>
      <webElementGuid>c582b8a7-6288-4159-a37f-e3812c73fa89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agentComment</value>
      <webElementGuid>2599f342-7299-4831-81ad-f836c6b74d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>7cb6aca5-0dc2-4ca4-9f73-581a9506645a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>agentComment-error</value>
      <webElementGuid>149c6ce8-e718-43eb-94f3-4dd620e65d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agentComment&quot;)</value>
      <webElementGuid>5217ae3c-78cf-436c-97be-e8536be2726f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='agentComment']</value>
      <webElementGuid>f3d3c7c9-4230-4ebe-bdd1-5c96c0bdbca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CollapseCR']/div/div[2]/div[2]/div/textarea</value>
      <webElementGuid>c1ff2136-e2b2-4b3f-9d81-b38f13a11114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>99fec904-cb7b-496d-99dd-6ccb752dcc93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'agentComment' and @name = 'agentComment']</value>
      <webElementGuid>4b272d33-5da1-4d22-b91f-bf50a82af078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
