<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>passengerName_PassengerDetails_TextBox</name>
   <tag></tag>
   <elementGuidId>99b6ce9d-6fd7-41f8-b94f-4a3aa2aed939</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#StringFormat_passengerName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='StringFormat_passengerName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#StringFormat_passengerName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37d249bd-d2b3-45cd-bec8-99a5493823cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm clToUpperCase input-validation-error</value>
      <webElementGuid>81038b56-ab6a-4786-b678-f113d3a3bf64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>213ba349-edc4-407c-bc15-09bcb240ecd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>Length must be less than or equal to 100 characters</value>
      <webElementGuid>609fd1e0-41f5-43e3-9f9e-9065fb8359e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>7c282783-50a7-42a4-8e3f-cf3d35c759c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StringFormat_passengerName</value>
      <webElementGuid>c73cb78c-8a2c-4fb0-a404-123cca5d8c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passengerName</value>
      <webElementGuid>febf2ed7-e29c-4996-a6de-cbe92e638285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PaxCardMain.updatePaxNameColor(this.value,true);</value>
      <webElementGuid>f7ed7e7b-2c2d-4528-8489-95a5d27e0d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45fb8663-c8dd-4c16-b6f4-bf9b8ab041c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>StringFormat_passengerName-error</value>
      <webElementGuid>9896f1ee-65de-48eb-9bc6-2c94bca21b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StringFormat_passengerName&quot;)</value>
      <webElementGuid>ddd0b8c9-6195-414a-a9ae-9c3017515f7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='StringFormat_passengerName']</value>
      <webElementGuid>8187ed6b-1429-47dc-b517-b45f75c39866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CollapseCP']/div/div[2]/input</value>
      <webElementGuid>d527ff88-42da-4493-b471-1f3f5951624f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div/div[2]/div/div[2]/input</value>
      <webElementGuid>80829a94-a831-49d8-94c6-7e55c9764fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'StringFormat_passengerName' and @name = 'passengerName' and @type = 'text']</value>
      <webElementGuid>8da68b95-6c33-4da3-8f54-1796d44c4684</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
