<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Field required</name>
   <tag></tag>
   <elementGuidId>e56ceb1c-ac99-47b6-9edf-857393b2fdcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EmailFormat_passengerEmail-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='EmailFormat_passengerEmail-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#EmailFormat_passengerEmail-error</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f9fd95e1-8894-4e87-9863-3f35b020cfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailFormat_passengerEmail-error</value>
      <webElementGuid>85177aea-e7c5-496c-9781-ff8f119483be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Field required</value>
      <webElementGuid>910dc44d-4e0f-4795-8c10-dc75bc5dff96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailFormat_passengerEmail-error&quot;)</value>
      <webElementGuid>6c6fa11e-07f7-4faa-bab2-7144e5ab90f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='EmailFormat_passengerEmail-error']</value>
      <webElementGuid>c3514e46-9475-4507-92f0-0e11126be20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CollapseCP']/div/div[3]/div/span/span</value>
      <webElementGuid>44feb5e3-04eb-470e-9b62-03456761481b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail Address'])[1]/following::span[2]</value>
      <webElementGuid>6190ffb0-6c9e-45bb-8f2e-279e1833ffda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Field required'])[2]/following::span[2]</value>
      <webElementGuid>7d57da10-867c-4c79-8439-70b886fa3964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::span[1]</value>
      <webElementGuid>83257b30-231e-4dd6-b468-6fd86e7f64e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::span[2]</value>
      <webElementGuid>16bc3e28-7f78-461b-b05e-e8eb304d5ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/span</value>
      <webElementGuid>761a8d3d-d7dc-4f68-bd09-dc360197f9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'EmailFormat_passengerEmail-error' and (text() = 'Field required' or . = 'Field required')]</value>
      <webElementGuid>69712fbf-e775-430a-99fe-f08e0daf01cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
