<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Success</name>
   <tag></tag>
   <elementGuidId>828022d6-c429-4318-9c7f-1568a7195e61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong.mr-auto.no-seleccionable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast_6021']/div/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Success&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>7e24afb1-5abe-432b-9589-4eefe4c0bc31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-auto no-seleccionable</value>
      <webElementGuid>b99f5ef1-1da4-4a7b-bbe6-92cd0bac9534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Success </value>
      <webElementGuid>8dc72ace-22b0-49b3-ad25-0e69da88b43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast_6021&quot;)/div[@class=&quot;toast-header toast-success&quot;]/strong[@class=&quot;mr-auto no-seleccionable&quot;]</value>
      <webElementGuid>c8bac7ac-0a7e-4467-ad4c-8f1fd52f4b34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast_6021']/div/strong</value>
      <webElementGuid>f475b1c6-7024-4898-86d4-44263896f194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In progress'])[1]/following::strong[1]</value>
      <webElementGuid>2bc450b0-bd1f-499c-b82e-9ef991673fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OFF'])[1]/following::strong[1]</value>
      <webElementGuid>8282a1bf-57a9-4e9e-910a-d83a2b084f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refund correctly sent.'])[1]/preceding::strong[1]</value>
      <webElementGuid>ac9062bf-4a3c-4413-8fdb-3ffe18d49e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Success']/parent::*</value>
      <webElementGuid>dbbcddc0-2b78-418e-8509-c70400231e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>c44dc791-948f-4326-8d17-c538d6146886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = ' Success ' or . = ' Success ')]</value>
      <webElementGuid>30458793-beaa-48d0-99f8-799b1634748e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
