<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_PassengerDetails_Select</name>
   <tag></tag>
   <elementGuidId>fec57a8d-05f2-4ae5-b629-9f5bfe328e96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#StringFormat_passengerTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='StringFormat_passengerTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#StringFormat_passengerTitle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bb171517-2486-4b9f-99eb-ee5841337767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm disabledInCaseRO input-validation-error</value>
      <webElementGuid>f160151d-a155-435f-98bc-1b6129b0fdf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6067619d-aaef-4bab-a982-695646bcd77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>Length must be less than or equal to 30 characters</value>
      <webElementGuid>18826f3f-78e7-4021-9290-d61b44ca27a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>3643b145-f444-4ddd-8544-2c54c63f4439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StringFormat_passengerTitle</value>
      <webElementGuid>4389de00-c63d-4e70-bbd5-a02075c4e83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passengerTitle</value>
      <webElementGuid>6c3d93a4-9e83-4138-8136-c4bc6ab4a79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>StringFormat_passengerTitle-error</value>
      <webElementGuid>312a4289-fb78-4a24-937e-8c724a102043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Mr
Mrs
Miss
Mstr
</value>
      <webElementGuid>fd8d7699-80a0-45ab-873e-8965ee18ba58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StringFormat_passengerTitle&quot;)</value>
      <webElementGuid>16bd59dd-2db4-4135-938b-d66aaf5b23f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='StringFormat_passengerTitle']</value>
      <webElementGuid>ca6f8c0b-74c2-4c0d-be58-c8b0d1f9949a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CollapseCP']/div/div/select</value>
      <webElementGuid>9d3adbbf-53aa-4e6f-9519-b27597336720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::select[1]</value>
      <webElementGuid>9662fce9-b8c4-43c5-90c8-59a2cf594a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger Details'])[1]/following::select[1]</value>
      <webElementGuid>6029e687-bbc1-4466-8ed3-b0afd1e4566d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Field required'])[1]/preceding::select[1]</value>
      <webElementGuid>3fb682c3-a1fe-4ef1-bfdb-70489ffef11d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger Name'])[1]/preceding::select[1]</value>
      <webElementGuid>04c2be43-2dcd-41a9-b058-6887df2089cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/select</value>
      <webElementGuid>eac36f51-3eba-4ff4-8c00-dab3a4316b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'StringFormat_passengerTitle' and @name = 'passengerTitle' and (text() = '
Mr
Mrs
Miss
Mstr
' or . = '
Mr
Mrs
Miss
Mstr
')]</value>
      <webElementGuid>70fad666-9355-4619-9306-edda0eccacaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
