<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Refund Search</name>
   <tag></tag>
   <elementGuidId>3c52e053-e823-4bc7-9491-bf5e652ebc68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_RefundSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu_RefundSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Refund Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed38f3db-7530-4cd2-a2e5-40cc21846489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_RefundSearch</value>
      <webElementGuid>552f3b10-c958-4291-9d80-ee4f5bac36c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>02da0ee1-712d-4889-8f87-6ce55110e894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/MozartTest/RefundSearch/Index</value>
      <webElementGuid>194ead87-2ca4-4823-a37d-6a1a9e69336c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Refund Search
                    </value>
      <webElementGuid>cb61a2d4-e308-4a2b-b126-390eb38785de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_RefundSearch&quot;)</value>
      <webElementGuid>60933f56-f8c5-41fb-b3bb-f019141eed78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_RefundSearch']</value>
      <webElementGuid>a38704dc-f0d0-49ec-8cb0-536f41ed45dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul/li/ul/li/a</value>
      <webElementGuid>90b80584-f2d8-4dab-afd2-d7e2532c2167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Refund Search')]</value>
      <webElementGuid>56243343-18b6-410d-9f47-38b2d093932a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mozart - Refund Management'])[1]/following::a[2]</value>
      <webElementGuid>192aa0d8-6083-40ef-91d8-c7d592b04a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Refund Search']/parent::*</value>
      <webElementGuid>5cec426f-3de6-45e6-82b1-052ad99cc141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/MozartTest/RefundSearch/Index')]</value>
      <webElementGuid>ccad83aa-7c5f-4115-b1c2-e67c72b68ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>e4ef877d-f3eb-4b47-baa3-5951f03006d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu_RefundSearch' and @href = '/MozartTest/RefundSearch/Index' and (text() = '
                        Refund Search
                    ' or . = '
                        Refund Search
                    ')]</value>
      <webElementGuid>032d87b4-6e7c-4b4c-a008-f27a1489d16c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
